on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: hosting205231.a2e76.netcup.net
        username: hubba-dev-pages
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*
          **/.github*/**
          .gitignore
          LICENSE
          README.md
